### ISSUE TITLE
Component system

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#105]
With a component system, I should be able to implement: Boulders, Bombs (#69), Fire, Corpses etc

I don't think Zemeroth needs a full-featured ECS solution (like [specs](https://github.com/slide-rs/specs)) as the game is turn-based. A bunch of `HashMap<ObjId, ComponentType>` will do the work fine.

See:
- https://gridbugs.org/programming-languages-make-terrible-game-engines
- https://gridbugs.org/modifying-entity-component-system-for-turn-based-games
- See https://github.com/rsaarelm/calx-ecs

**Comment by vitvakatu** [comment]
What about froggy?)

**Comment by ozkriff** [comment]
Nope, I think that froggy is an overkill for this task too.

**Comment by ozkriff** [comment]
Draft: https://play.rust-lang.org/?gist=ec459f6ec32ddc899f788a1565e44edf

**Comment by ozkriff** [comment]
Working in the [WIP_i105_components](https://github.com/ozkriff/zemeroth/tree/WIP_i105_components) branch.

**Comment by ozkriff** [comment]
Rancor seems to work fine, but I see two issues:

1) Too many braces in RON file with prototypes
2) Duplication of data between initial values of `strength` and `base_strength` fields (same for `base_moves`, `base_attacks`, `base_jokers`)

```cpp
({
    "swordsman": [
        Strength((
            base_strength: (4),
            strength: (4),
        )),
        Agent((
            moves: (1),
            attacks: (1),
            jokers: (1),
            reactive_attacks: (1),
            attack_distance: (1),
            move_points: (3),
            base_moves: (1),
            base_attacks: (1),
            base_jokers: (1),
        )),
    ],
})
```

But I'll create separate issues for this problems.
