### ISSUE TITLE
Android: Game is to dark on some devices

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#107]
![screenshot_20170909-081542](https://user-images.githubusercontent.com/662976/30237374-3cc657de-9539-11e7-8375-1d2ea6c92f04.png) VS ![](http://i.imgur.com/0w2yQuY.png)

I have no idea why. **Help**.

See:
- https://github.com/ozkriff/zoc/issues/200 - Same issue of ZoC

**Comment by vitvakatu** [comment]
Famous srgb bug in gfx?

**Comment by ozkriff** [comment]
Yeah. But I'm not sure if the bug is _in_ gfx - maybe I just use wrong parameters somewhere.

**Comment by ozkriff** [comment]
Closing this as there's no android build for now (#247)
