### ISSUE TITLE
Publish `zcomponents` 0.1 on crates.io

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#143]
Mostly to claim the name.

**Comment by diegor8** [comment]
any way i can help ? i am using this package to teach myself to program games in rust , and possibly make a series of tutorials / convince my peers to try this language

**Comment by ozkriff** [comment]
Oh, sorry. I've totally forgotten about this issue.

https://crates.io/crates/zcomponents
https://docs.rs/zcomponents
