### ISSUE TITLE
Fix OSX

### ISSUE THREAD

**Issue by GooseDB** [ozkriff/zemeroth#182]
Кварк сказал, что 27 строчка в hate/src/context.rs не нравится и надо срочно исправлять)

`Api::OpenGl` => "#version `120\n".into(),`

**Comment by ozkriff** [comment]
https://github.com/ozkriff/zemeroth/commit/cc3c4aff243335cf - this commit breaks the OSX build. Reverting it for now.

Update commit is stored in https://github.com/ozkriff/zemeroth/tree/gfx_v0_17 branch
