### ISSUE TITLE
RON: Use `implicit_some` and `unwrap_newtypes` extensions

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#187]
See https://github.com/ron-rs/ron/pull/75 & https://github.com/ron-rs/ron/pull/72

`#![enable(implicit_some)]`
`#![enable(unwrap_newtypes)]`

**Comment by ozkriff** [comment]
Waiting for a new version of RON on crates.io: https://crates.io/crates/ron

**Comment by ozkriff** [comment]
ron 0.1.7 is out!

**Comment by ozkriff** [comment]
Closed by https://github.com/ozkriff/zemeroth_assets/commit/f43c09e1f55a8c57f5de2eb5d54b7ba7c0a3ce62

**Comment by ozkriff** [comment]
I don't have any `Some` fields for now.

**Comment by Boscop** [comment]
@ozkriff How can I use this? If I put those two attributes in my ron file, I get a parser error. Has the syntax for these attributes changed?
