### ISSUE TITLE
Timed effects should be commutative

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#286]
![Illustration with multiple bombs](https://i.imgur.com/ZuLn7CEt.png)
Each of these bombs will explode at the beginning of the next turn, but in what order?
The order is very important as the explosions push back objects - if the first explosion is on the left, an agent will be damaged by the right bomb too.

Pushback is not the only possible effect suffering from this. Other possible examples of non-commutative effects: teleportation, armor-breaking acid, immunity to damage, etc?

I see two possible ways to solve this:
1) "Into the Breach"-like approach with explicit numbers
2) Forbid non-commutative effects

[![Into the breach screenshot with explicit order numbers](https://i.imgur.com/FDbvENKt.png)](https://i.imgur.com/2mO4M6p.png)
^ ItB's approach looks like this. Technically it's possible, but I don't think that it fits for Zemeroth as it's not a core mechanic.

So, I'm taking the latter way. The plan is to have three groups of objects with effects:

1) Objects with immediate effects - they can have non-commutative effects
2) General objects with timed effects - only commutative effects allowed.
3) Special rare timed objects - can do whatever they want, only allowed as unique boss abilities, work in their own special phase.

**Comment by shmutalov** [comment]
+ Will bomb explosion push neighbor bombs? Think of it

**Comment by ozkriff** [comment]
@shmutalov yep, it's really strange that pushbacks don't interact with other bombs. Atm, they only push objects with `agent` component.

Though I don't want to push boulders around so easily, so I need to introduce something like `weight` component and only push "light" objects. I'll create another issue for that.
