### ISSUE TITLE
`weight` component

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#291]
https://github.com/ozkriff/zemeroth/issues/286#issuecomment-400240023

shmutalov:
> Will bomb explosion push neighbor bombs?

ozkriff:
> yep, it's really strange that pushbacks don't interact with other bombs. Atm, they only push objects with agent component.
>
> Though I don't want to push boulders around so easily, so I need to introduce something like `weight` component and only push "light" objects. I'll create another issue for that.

-------

Weight table:

1) normal objects (examples: normal agents, bombs)
2) heavy objects (examples: heavy agents, boulders)
3) totally immovable objects

Obviously, push effect should get similar "strength" parameter.

**Comment by ozkriff** [comment]
Thought: maybe just add a field to blocker component?

**Comment by Vrixyz** [comment]
I might give this issue a try, in the meantime I'm writing here what I understand from the possible impacts, for future reference or if someone else wants to tackle that:

- `push effect` from this issue description actually refers to "Knockback" effect in the code
- `Strength` parameter would be implemented the same way as "Heal" ability
- `Weight` component (or `blocker`) parameter would be/contains an enum to match the specified weigth table

**Comment by ozkriff** [comment]
> ... I'm writing here what I understand from the possible impacts ...

I haven't fleshed the exact plan for this feature out yet, but this looks correct.

> I might give this issue a try ...

Great! Feel free to DM me on Discord or gitter if you want to discuss any details!
