### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by StyMaar** [ozkriff/zemeroth#310]
On today's master (https://github.com/ozkriff/zemeroth/commit/d218d38adfc67dd244d8658b74147bc461dc147b) when pressing «end turn».

(I launched the game twice, it happened every time on the first «end turn»).

> thread 'main' panicked at 'no entry found for key', libcore/option.rs:960:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::option::expect_failed
             at libcore/option.rs:960
   9: <core::option::Option<T>>::expect
             at /checkout/src/libcore/option.rs:312
  10: <std::collections::hash::map::HashMap<K, V, S> as core::ops::index::Index<&'a Q>>::index
             at /checkout/src/libstd/collections/hash/map.rs:1547
  11: zemeroth::core::state::private::State::prototype_for
             at src/core/state.rs:58
  12: zemeroth::core::execute::effect_create_object
             at src/core/execute.rs:856
  13: zemeroth::core::execute::throw_bomb
             at src/core/execute.rs:892
  14: zemeroth::core::execute::execute_use_ability_bomb_damage
             at src/core/execute.rs:930
  15: zemeroth::core::execute::execute_use_ability
             at src/core/execute.rs:981
  16: zemeroth::core::execute::execute
             at src/core/execute.rs:37
  17: zemeroth::screen::battle::Battle::do_command_inner
             at src/screen/battle/mod.rs:292
  18: zemeroth::screen::battle::Battle::do_ai
             at src/screen/battle/mod.rs:255
  19: zemeroth::screen::battle::Battle::end_turn
             at src/screen/battle/mod.rs:244
  20: <zemeroth::screen::battle::Battle as zemeroth::screen::Screen>::click
             at src/screen/battle/mod.rs:480
  21: zemeroth::screen::Screens::click
             at src/screen/mod.rs:61
  22: <zemeroth::MainState as ggez::event::EventHandler>::mouse_button_up_event
             at src/main.rs:83
  23: ggez::event::run
             at /home/stymaar/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/event.rs:243
  24: zemeroth::main
             at src/main.rs:108
  25: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  26: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  27: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  28: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:397
             at libstd/rt.rs:58
  29: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  30: main
  31: __libc_start_main
  32: _start

**Comment by StyMaar** [comment]
(I haven't played the game for two weeks, the bug could be quite old)

**Comment by ozkriff** [comment]
Hi :) Make sure that you are using the latest version of https://github.com/ozkriff/zemeroth_assets repo

**Comment by StyMaar** [comment]
Well caught. That fixes the problem, thanks :).

**Comment by ozkriff** [comment]
Reminds me to implement https://github.com/ozkriff/zemeroth/issues/109

**Comment by StyMaar** [comment]
Why are assets versioned out of the main git tree anyway ?

**Comment by ozkriff** [comment]
Because git isn't suited for working with binary files without [LFS](https://git-lfs.github.com/) and github's free plan for LFS is useless ([only 1GiB of **bandwidth** quota](https://help.github.com/articles/about-storage-and-bandwidth-usage/#bandwidth-quota)).

Of course, Zemeroth isn't a big game and doesn't have many assets to really create some problems (atm or in the foreseeable future). But I still see mixing code+assets (without LFS/annex/etc) a really dirty hack that may end up badly in a long term perspective.

Storing assets in another repo is a lesser evil as I can easily move them to other place or cut down some repo's history at any moment.

End users shouldn't suffer from this anyway - they are supposed to use https://github.com/ozkriff/zemeroth/releases
