### ISSUE TITLE
[Regression] Flickering animations 

### ISSUE THREAD

**Issue by StyMaar** [ozkriff/zemeroth#312]
Animations used to be smooth (two weeks ago), but [now](https://github.com/ozkriff/zemeroth/commit/d218d38adfc67dd244d8658b74147bc461dc147b) they aren't.

**Comment by ozkriff** [comment]
That's strange, I don't recall changing anything graphics-related (https://github.com/ozkriff/zemeroth/compare/b0ddd4d9d...master).

Are you 100% sure that you're using a release build (`cargo build --release`/`cargo run --release`)?

**Comment by StyMaar** [comment]
Oops.

You were right indeed.
