### ISSUE TITLE
Mouse clicks off

### ISSUE THREAD

**Issue by daimeng** [ozkriff/zemeroth#408]
The game looks awesome. I am playing on mac pro. Everything compiles and launches fine, however clicks on the screen seems to be offset or scaled incorrectly.

For example here is where menu is vs where I need to click to hit the corresponding button:
```
____________________________
|                          |
|      [1demo battle]      |
|      [2campaign]         |
|      [3strategy mode]   1|
|      [4exit]            2|
|_________________________3|
```
I'd be interested to do more digging when I have time, but fyi I am a rust newbie so my debugging skills are weak.

More details:
- Applies on game screens as well.
- I can click exit button at top left corner of screen fine, which is why I thought it could be scaling issue.
- Possibly related to ggez + hdpi?

**Comment by ozkriff** [comment]
https://github.com/ggez/ggez/issues/587 - looks like it's still an issue on GGEZ v0.5.0-rc.1

**Comment by ozkriff** [comment]
https://github.com/ggez/ggez/commit/2f02c72cf31401a1e6ab55edc745f6227c99fb67 - agrhh.. I'm not sure what to do with the macOS version of Zemeroth now. Maybe some volunteer with mac hardware will fix GGEZ's (winit's?) issues? :(
