### ISSUE TITLE
häte: Check if hidpi works on linux

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#44]
See

- https://docs.rs/glutin/0.9/glutin/struct.Window.html#method.get_inner_size
- https://docs.rs/glutin/0.9/glutin/struct.Window.html#method.get_inner_size_points
- https://docs.rs/glutin/0.9/glutin/struct.Window.html#method.hidpi_factor

**Comment by ozkriff** [comment]
See also https://github.com/tomaka/glutin/issues/903

**Comment by umurgdk** [comment]
This PR should fix it: https://github.com/tomaka/winit/pull/245

**Comment by ozkriff** [comment]
Closed by https://github.com/ozkriff/zemeroth/pull/163 (I hope)
