### ISSUE TITLE
rendering ratio issue

### ISSUE THREAD

**Issue by debris** [ozkriff/zemeroth#484]
I just tested master branch on `mac os 10.14.3` and it seems like there is a bug in rendering

<img width="912" alt="Screenshot 2019-06-07 at 16 50 46" src="https://user-images.githubusercontent.com/2613714/59092569-724de600-8944-11e9-9ff8-3c451215dbf0.png">
<img width="825" alt="Screenshot 2019-06-07 at 16 46 26" src="https://user-images.githubusercontent.com/2613714/59092450-2733d300-8944-11e9-87cf-f2c900a46020.png">
<img width="464" alt="Screenshot 2019-06-07 at 16 46 15" src="https://user-images.githubusercontent.com/2613714/59092454-29962d00-8944-11e9-9033-b3d2aec93fe4.png">

It's also difficult to press buttons, as button touch zones are a bit off (I guess, they are exactly where Sprites are supposed to be rendered.

I was trying to debug the problem, but it was a bit too time consuming. I guess the problem is caused by aspect ratio of the screen not being correctly used (or not used) in `draw` function.

**Comment by ozkriff** [comment]
Seems to be related to https://github.com/ozkriff/zemeroth/issues/408 (_"Mouse clicks off"_)

**Comment by ozkriff** [comment]
@debris This issue can be closed too now, right?

**Comment by Vrixyz** [comment]
I confirm on macOS 10.14.6 it runs fine (it appears squished when changing windows size, but then fixes itself) : 
<img width="912" alt="Capture d’écran 2019-11-08 à 22 36 56" src="https://user-images.githubusercontent.com/2290685/68512354-745ffc00-0278-11ea-8091-02075912df2d.png">

<img width="1007" alt="Capture d’écran 2019-11-08 à 22 40 20" src="https://user-images.githubusercontent.com/2290685/68512464-c56ff000-0278-11ea-8d34-2b5bac32f627.png">
