### ISSUE TITLE
Add git submodule for assets

### ISSUE THREAD

**Issue by bjorn3** [ozkriff/zemeroth#529]
That way you don't have to manually clone the assets repo. It also prevents accidentally combining different versions of the assets and the executable.

**Comment by ozkriff** [comment]
Oh, I forgot to comment on this issue, sorry. :grimacing: 

I had a terrible experience with git submodules and would really like to avoid them. But in any case, I decided to [move all assets into this repo](https://github.com/ozkriff/zemeroth/issues/520) (#520).
