### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#543]
Maybe GA will be able to replace Travis, Appveyor, and Circle-CI altogether? I'll try to experiment with it.

Links:
- https://github.com/actions-rs

**Comment by nickelc** [comment]
Hey, I'm working on GitHub workflows for CI and release for zemeroth.

The [CI] workflow is based on the Travis and Appveyor setup and the [Release] workflow is listing on published releases to build and upload all the artifacts.

#### Latest runs
CI: https://github.com/nickelc/zemeroth/runs/349688504
Release: https://github.com/nickelc/zemeroth/runs/349633617
Artifacts: https://github.com/nickelc/zemeroth/releases/tag/v0.7.0

[CI]: https://github.com/nickelc/zemeroth/blob/gh-actions/.github/workflows/ci.yml
[Release]: https://github.com/nickelc/zemeroth/blob/gh-actions/.github/workflows/release.yml

**Comment by ozkriff** [comment]
Closed by https://github.com/ozkriff/zemeroth/pull/549

**Comment by ozkriff** [comment]
It's a little bit sad that GA doesn't support something like allow_failure (yet?) but it's not a critical thing.

- https://github.com/ozkriff/zemeroth/pull/549#discussion_r365617227
- https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033

Let's live-test GA for a while now. :)
