### ISSUE TITLE
/usr/bin/ld : cannot find -lGL ___ /usr/bin/ld : cannot find -lXi

### ISSUE THREAD

**Issue by laticoda** [ozkriff/zemeroth#579]
Hello, i havealready installed build-essential and assets are in right place ;
 when i try to cargo build --release i get:

**error: linking with `cc` failed: exit code: 1**
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.0.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.1.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.10.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.11.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.12.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.13.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.14.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.15.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.2.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.3.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.4.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.5.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.6.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.7.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.8.rcgu.o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.zemeroth.cxe0r31s-cgu.9.rcgu.o" "-o" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/zemeroth-2a8deb94498c868a.458op3t69xgnq6d8.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps" "-L" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libenv_logger-020bfdf6267bf909.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libtermcolor-0da8b3c133a36a7c.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libatty-26f94e5b95bc71f7.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libhumantime-a611f3164947d731.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libquick_error-af8df6311fa98e72.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libregex-d82dfc7c71c05eeb.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libthread_local-a84670340260f076.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblazy_static-14afa302397059c5.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libregex_syntax-cefc061ecdc78575.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libaho_corasick-d5b5b2c4e252483c.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libmemchr-a821e32d00d5e3d0.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libron-998274975df389d1.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libbase64-4f9f3473f0d62904.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libzscene-2ef59e0cd7d54ac9.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libzgui-8f54d0fdc237840c.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libquad_rand-2f799ca1e68b9c53.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum-d10e932ad36579af.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum_complex-a9acfe6d163babfb.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand-357ebf4d704761cf.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_chacha-cf07140b121aad00.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libppv_lite86-149557f97210c15e.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_core-3d428929d1ca499a.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libgetrandom-fd485c8893166d74.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libzcomponents-96e2eca81e0b25b4.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblog-4dfe60008f5d0244.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libserde-3b92d6ea9fdd8bc7.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libgood_web_game-3eccd5427c1961b0.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libimage-c79aeeb4ebe08502.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libpng-8083cbff90c1e662.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libdeflate-c7ae1a3ee04a02be.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libinflate-e6aa18df6ab35ed8.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libadler32-899a62adc1b73bb7.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libcrc32fast-c1c470a9af72effc.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum_rational-4539229413816360.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum_iter-554b90aaff11550f.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum_integer-0b7dd474bc94fbb9.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libbyteorder-ae8be6ae0f3ee564.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libtar-6c7233645835df95.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libfiletime-ba08171e63159b9f.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libcfg_if-64c0d2409cb56520.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libbitflags-e261184c77ad1a7f.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblyon-183821cc73c8885a.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblyon_algorithms-1fd94ed5cca42c9f.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblyon_tessellation-594ce3c538ac66da.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libsid-658c72aa926a12a8.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblyon_path-8f3f419b90b84712.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblyon_geom-6dd44d34bf1412fa.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libeuclid-4867df6dc374b758.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum_traits-40c36e36cd97837f.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libarrayvec-c18db53b63c204d4.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnodrop-a0abd9fa8844f5e0.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libminiquad_text_rusttype-17bc53924a8046d1.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librusttype-732e69bd6e38cb6f.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libab_glyph_rasterizer-10f3b39fda730219.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libowned_ttf_parser-9b7f699981a9dd62.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libttf_parser-091b8f5fdfc6e80c.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libminiquad-ea7910e1338bb2b1.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libsapp_linux-e5a656eac884d4f0.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libcgmath-43963b3dabbd9a56.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand-b20777cb61728b55.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_xorshift-e582492bd2168bce.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_pcg-a339ea17dfa29eb6.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_hc-2a7862ee160996fa.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_chacha-74f7b56b16ab4878.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_isaac-6d4e5c4018cfc086.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_core-1d760f77e96e81d6.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_os-b2501265eac7fd19.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/liblibc-1a9983877aa79647.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_jitter-c787f389e6ac707a.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/librand_core-72565076fa5b8ad0.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libmint-416c15456d47e628.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libapprox-f2dc7cf69ec23345.rlib" "/media/laticoda/slowdisk/zemeroth-master/target/release/deps/libnum_traits-0e84a4d8284bf66e.rlib" "-Wl,--start-group" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6640d3868fa846e8.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-48481e446108229f.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-bfdf9e1c331f914a.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-991e68a3d0300af6.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-74304cfed66bbabf.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-5db30a83f5489d12.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-a106c3f62654e72c.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3d6b30695af38106.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-d8f11f6bb46ba3ee.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-60c81ab95e289dd1.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-fd1a416f10d6c43d.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-4a2bd2b60cccd1fb.rlib" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-7ea8ebc630055039.rlib" "-Wl,--end-group" "/home/laticoda/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f7cd12d3ecd59a89.rlib" "-Wl,-Bdynamic" "-lGL" "-lX11" "-lXi" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  **= note: /usr/bin/ld : cannot find -lGL
          /usr/bin/ld : cannot find -lXi
          collect2: error: ld returned 1 exit status**

**Comment by ozkriff** [comment]
Have you installed the [required system deps](https://github.com/not-fl3/miniquad/tree/faabb54d3#building-examples)?

```bash
sudo apt install libx11-dev libxi-dev libgl1-mesa-dev
```

**Comment by laticoda** [comment]
I think it helped , but now , after rebooting:

cargo run --release
    Finished release [optimized] target(s) in 1.56s
     Running `target/release/zemeroth`
thread 'main' panicked at 'No such file: ".checksum.md5"', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: good_web_game::filesystem::open
  14: zemeroth::utils::read_file
  15: zemeroth::utils::check_assets_hash
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: miniquad::init
  18: sapp_linux::_sapp_run
  19: sapp_run
  20: miniquad::start
  21: zemeroth::main
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  25: std::panicking::try
             at src/libstd/panicking.rs:274
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  28: main
  29: __libc_start_main
  30: _start

**Comment by ozkriff** [comment]
Weird. Are you sure that the assets are in `assets` dir?

> ```bash
> git clone https://github.com/ozkriff/zemeroth_assets assets
> ```

**Comment by laticoda** [comment]
It works, very good looking, thanks !

Le ven. 3 juil. 2020 à 21:31, Andrey Lesnikov <notifications@github.com> a
écrit :
