### ISSUE TITLE
can i use it to develop my 2d game project? thx

### ISSUE THREAD

**Issue by rhettli** [ozkriff/zemeroth#653]
as title say , this is a 2d game engine?

**Comment by grzi** [comment]
Answer from the readme : 

> Zemeroth is a turn-based hexagonal tactical game written in Rust.
> The key external dependency of Zemeroth is **macroquad/miniquad**.

**Comment by ozkriff** [comment]
Yeah, Zemeroth doesn't have any reusable engine (on top of macroquad) that is clearly separated from the game's code.
