### ISSUE TITLE
include license file in zcomponents crate source

### ISSUE THREAD

**Issue by remilauzier** [ozkriff/zemeroth#659]
Hi. i am packaging zcomponents in fedora and it would be easier to have the file include in the crate source.
Here the fedora license guide: https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
Here the fedora guideline for rust: https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/

**Comment by ozkriff** [comment]
@remilauzier done!

**Comment by remilauzier** [comment]
Thanks!
