### ISSUE TITLE
Display short unit info under their map sprites

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#95]
Something like this: ![](http://www.lki.ru/Txt/Front/0803/Codex/Main/dwarves.jpg)

But with just a few numbers for now.

**Comment by ozkriff** [comment]
![image](https://user-images.githubusercontent.com/662976/29752295-0c6b0fb4-8b64-11e7-9dce-1e08e2861cfb.png)

Hmm, numbers look stupid.

I should try some kind of colored circles.

**Comment by ozkriff** [comment]
![image](https://user-images.githubusercontent.com/662976/29753295-282437ea-8b77-11e7-8592-757b27140894.png)

Something like this?

**Comment by vitvakatu** [comment]
Maybe to play with positioning a bit? Green dots aren't well visible. Try to place them at bottom-right.

**Comment by ozkriff** [comment]
Like this?

![](http://i.imgur.com/dVMstcL.png)

**Comment by ozkriff** [comment]
![](http://i.imgur.com/WZxwwjA.gif)

**Comment by ozkriff** [comment]
Almost there. Cleaning up the code.
